function kana2manyougana(inpstr) {

    txt=inpstr;
    txt=txt.replaceAll("ア", "㢌")
    txt=txt.replaceAll("ァ", "阿")
    txt=txt.replaceAll("イ", "洢")
    txt=txt.replaceAll("ィ", "伊")
    txt=txt.replaceAll("ウ", "宇")
    txt=txt.replaceAll("ゥ", "宀")
    txt=txt.replaceAll("ヴ", "珷")
    txt=txt.replaceAll("エ", "茳")
    txt=txt.replaceAll("ェ", "𢓁")
    txt=txt.replaceAll("オ", "於")
    txt=txt.replaceAll("ォ", "个")

    txt=txt.replaceAll("カ", "乫")
    txt=txt.replaceAll("キ", "耭")
    txt=txt.replaceAll("ク", "㝌")
    txt=txt.replaceAll("ケ", "祄")
    txt=txt.replaceAll("コ", "玘")

    txt=txt.replaceAll("ガ", "㔖")
    txt=txt.replaceAll("ギ", "僟")
    txt=txt.replaceAll("グ", "㡱")
    txt=txt.replaceAll("ゲ", "紒")
    txt=txt.replaceAll("ゴ", "䓽")

    txt=txt.replaceAll("サ", "橵")
    txt=txt.replaceAll("シ", "椘")
    txt=txt.replaceAll("ス", "蕦")
    txt=txt.replaceAll("セ", "朑")
    txt=txt.replaceAll("ソ", "噌")

    txt=txt.replaceAll("ザ", "奢")
    txt=txt.replaceAll("ジ", "餌")
    txt=txt.replaceAll("ズ", "殊")
    txt=txt.replaceAll("ゼ", "泄")
    txt=txt.replaceAll("ゾ", "層")

    txt=txt.replaceAll("タ", "䇋")
    txt=txt.replaceAll("チ", "竏")
    txt=txt.replaceAll("ツ", "栦")
    txt=txt.replaceAll("ッ", "汇")
    txt=txt.replaceAll("テ", "祆")
    txt=txt.replaceAll("ト", "杫")

    txt=txt.replaceAll("ダ", "汏")
    txt=txt.replaceAll("ヂ", "䊹")
    txt=txt.replaceAll("ヅ", "銂")
    txt=txt.replaceAll("デ", "䀖")
    txt=txt.replaceAll("ド", "度")

    txt=txt.replaceAll("ナ", "奈")
    txt=txt.replaceAll("ニ", "仁")
    txt=txt.replaceAll("ヌ", "奴")
    txt=txt.replaceAll("ネ", "祢")
    txt=txt.replaceAll("ノ", "乃")
    txt=txt.replaceAll("ン", "尓")

    txt=txt.replaceAll("ハ", "扒")
    txt=txt.replaceAll("ヒ", "仳")
    txt=txt.replaceAll("フ", "㳅")
    txt=txt.replaceAll("ヘ", "蔀")
    txt=txt.replaceAll("ホ", "湺")

    txt=txt.replaceAll("バ", "婆")
    txt=txt.replaceAll("ビ", "避")
    txt=txt.replaceAll("ブ", "枌")
    txt=txt.replaceAll("ベ", "廍")
    txt=txt.replaceAll("ボ", "帆")

    txt=txt.replaceAll("パ", "紦")
    txt=txt.replaceAll("ピ", "畢")
    txt=txt.replaceAll("プ", "蒲")
    txt=txt.replaceAll("ペ", "䋶")
    txt=txt.replaceAll("ポ", "葡")

    txt=txt.replaceAll("マ", "抹")
    txt=txt.replaceAll("ミ", "仨")
    txt=txt.replaceAll("ム", "桙")
    txt=txt.replaceAll("メ", "䎟")
    txt=txt.replaceAll("モ", "䋃")

    txt=txt.replaceAll("ヤ", "酏")
    txt=txt.replaceAll("ャ", "彵")
    txt=txt.replaceAll("ユ", "䌷")
    txt=txt.replaceAll("ュ", "苖")
    txt=txt.replaceAll("ヨ", "與")
    txt=txt.replaceAll("ョ", "㧮")

    txt=txt.replaceAll("ラ", "琅")
    txt=txt.replaceAll("リ", "浰")
    txt=txt.replaceAll("ル", "蓅")
    txt=txt.replaceAll("レ", "礼")
    txt=txt.replaceAll("ロ", "絽")

    txt=txt.replaceAll("ワ", "萂")
    txt=txt.replaceAll("ヰ", "井")
    txt=txt.replaceAll("ヱ", "恵")
    txt=txt.replaceAll("ヲ", "乎")

    txt=txt.replaceAll("あ", "銨")
    txt=txt.replaceAll("ぁ", "侒")
    txt=txt.replaceAll("い", "拟")
    txt=txt.replaceAll("ぃ", "泤")
    txt=txt.replaceAll("う", "宇")
    txt=txt.replaceAll("ぅ", "宀")
    txt=txt.replaceAll("ゔ", "碔")
    txt=txt.replaceAll("え", "庡")
    txt=txt.replaceAll("ぇ", "㳖")
    txt=txt.replaceAll("お", "䢍")
    txt=txt.replaceAll("ぉ", "汸")

    txt=txt.replaceAll("か", "㖙")
    txt=txt.replaceAll("き", "耭")
    txt=txt.replaceAll("く", "㝌")
    txt=txt.replaceAll("け", "籵")
    txt=txt.replaceAll("こ", "玘")

    txt=txt.replaceAll("が", "賀")
    txt=txt.replaceAll("ぎ", "僟")
    txt=txt.replaceAll("ぐ", "㡱")
    txt=txt.replaceAll("げ", "牙")
    txt=txt.replaceAll("ご", "䓽")

    txt=txt.replaceAll("さ", "左")
    txt=txt.replaceAll("し", "之")
    txt=txt.replaceAll("す", "忖")
    txt=txt.replaceAll("せ", "朑")
    txt=txt.replaceAll("そ", "噌")

    txt=txt.replaceAll("ざ", "奢")
    txt=txt.replaceAll("じ", "餌")
    txt=txt.replaceAll("ず", "紂")
    txt=txt.replaceAll("ぜ", "泄")
    txt=txt.replaceAll("ぞ", "層")

    txt=txt.replaceAll("た", "㣖")
    txt=txt.replaceAll("ち", "痴")
    txt=txt.replaceAll("つ", "杊")
    txt=txt.replaceAll("っ", "汇")
    txt=txt.replaceAll("て", "祆")
    txt=txt.replaceAll("と", "止")

    txt=txt.replaceAll("だ", "駄")
    txt=txt.replaceAll("ぢ", "恥")
    txt=txt.replaceAll("づ", "汌")
    txt=txt.replaceAll("で", "泥")
    txt=txt.replaceAll("ど", "度")

    txt=txt.replaceAll("な", "奈")
    txt=txt.replaceAll("に", "芢")
    txt=txt.replaceAll("ぬ", "怒")
    txt=txt.replaceAll("ね", "祢")
    txt=txt.replaceAll("の", "㲌")
    txt=txt.replaceAll("ん", "无")

    txt=txt.replaceAll("は", "𨨏")
    txt=txt.replaceAll("ひ", "仳")
    txt=txt.replaceAll("ふ", "㳅")
    txt=txt.replaceAll("へ", "蔀")
    txt=txt.replaceAll("ほ", "湺")

    txt=txt.replaceAll("ば", "蔢")
    txt=txt.replaceAll("び", "䓺")
    txt=txt.replaceAll("ぶ", "枌")
    txt=txt.replaceAll("べ", "廍")
    txt=txt.replaceAll("ぼ", "緥")

    txt=txt.replaceAll("ぱ", "㿬")
    txt=txt.replaceAll("ぴ", "畢")
    txt=txt.replaceAll("ぷ", "蚡")
    txt=txt.replaceAll("ぺ", "䋶")
    txt=txt.replaceAll("ぽ", "葡")

    txt=txt.replaceAll("ま", "抹")
    txt=txt.replaceAll("み", "鎂")
    txt=txt.replaceAll("む", "陚")
    txt=txt.replaceAll("め", "䎟")
    txt=txt.replaceAll("も", "䋃")

    txt=txt.replaceAll("や", "酏")
    txt=txt.replaceAll("ゃ", "彵")
    txt=txt.replaceAll("ゆ", "䌷")
    txt=txt.replaceAll("ゅ", "苖")
    txt=txt.replaceAll("よ", "屿")
    txt=txt.replaceAll("ょ", "𥫣")

    txt=txt.replaceAll("ら", "琅")
    txt=txt.replaceAll("り", "浰")
    txt=txt.replaceAll("る", "蒥")
    txt=txt.replaceAll("れ", "礼")
    txt=txt.replaceAll("ろ", "絽")

    txt=txt.replaceAll("わ", "萂")
    txt=txt.replaceAll("ゐ", "爲")
    txt=txt.replaceAll("ゑ", "恵")
    txt=txt.replaceAll("を", "闧")

    document.getElementById('outputix').innerHTML=txt;
    console.log(txt);
}
